### ISSUE TITLE
Friday is likely not the best day for our calls

### ISSUE THREAD

**Issue by gnidan** [ethdebug/format#11]
What's a better schedule for our biweekly syncs?

**Comment by gnidan** [comment]
@jtoman to use technology to come to consensus

**Comment by jtoman** [comment]
Here is the link: https://whenisgood.net/xyishih

Please fill out this survey, being absolutely sure to set your local timezone correctly!

When selecting your availability, please ignore the actual dates, and just focus on the days of the week (the whenisgood app does not allow selecting generic days of the week.)

**Comment by gnidan** [comment]
We now meet Wednesdays at 12:30 ET [GMT-4 right now]. Please reach out in the [ethdebug Matrix.chat](https://matrix.to/#/#ethdebug:matrix.org) if you'd like a calendar invite!
