### ISSUE TITLE
Website should have an interactive playground editor for validating schemas

### ISSUE THREAD

**Issue by gnidan** [ethdebug/format#64]
It would be nice for there to be a way for people trying to familiarize themselves with this format to be able to type or paste JSON values and see errors if there's a validation problem.

**Comment by raxhvl** [comment]
Do you have a reference for how this should work?

**Comment by gnidan** [comment]
> Do you have a reference for how this should work?

Not quite a reference, but let me explain what I'm thinking a bit:
- We should add a new `packages/validate/` that defines the `@ethdebug/format-validate` package. I already made the `@ethdebug/format` package in `packages/format/`, which is just an NPM package to distribute the schemas themselves. I figure we should have this validate package be separate, so the schemas package doesn't add extra deps. This validate package should use hyperjump's libraries (the way the tests package does now)
- Inside `packages/web`, we should make a new component (likely in `src/components/Playground` or such). This Playground component would have a JSON editor and it would validate and report errors when the text input changes.
- I'm thinking that we want to have some kind of drop-down to select which schema to validate (on a single /spec/playground page), or maybe each schema page should have its own schema-specific playground.

Does this make sense? I haven't really thought this through in much detail yet. There might be another option (besides using the hyperjump libraries), which would be to use the Monaco editor's custom validation logic... I think this approach would be nice if it's easy to get working, because Monaco editor gives you red squiggly lines (as opposed to just a separate errors list)

**Comment by raxhvl** [comment]
>Inside packages/web, we should make a new component (likely in src/components/Playground or such). This Playground component would have a JSON editor and it would validate and report errors when the text input changes.

You mean something like this: https://json-schema.hyperjump.io/

**Comment by gnidan** [comment]
> >Inside packages/web, we should make a new component (likely in src/components/Playground or such). This Playground component would have a JSON editor and it would validate and report errors when the text input changes.
> 
> 
> 
> You mean something like this: https://json-schema.hyperjump.io/

Yep exactly! Except no need for the left-side pane: instead I'm thinking that we have a single code editor + a drop-down for which schema you want to validate (ethdebug/format/type, ethdebug/format/type/elementary/uint, etc.) Maybe this dropdown could be searchable, or have other nice features.

Basically I just want to make it as easy as possible to learn this format... someone who reads the section on array types might want to try writing a complex nested array of arrays, and it would be nice if they could check for validation errors right on our website.

**Comment by raxhvl** [comment]
> I'm probably biased, but I'm imagining the simplicity of https://gnidan.github.io/abi-to-sol (the left hand side specifically)
Love it! Let me give it a shot. I'll come back more ideas early next week.

**Comment by gnidan** [comment]
> Love it! Let me give it a shot. I'll come back with more ideas early next week.

Awesome! Let me know how you get on. I put together this mockup to show the kind of layout I'm thinking for this case:

![image](https://github.com/ethdebug/format/assets/151065/f7e65a04-f4b1-4ef4-ba18-8d084428f561)

**Comment by raxhvl** [comment]
I made a quick prototype: https://eth-debug-playground.vercel.app/

Let me know what you think

**Comment by gnidan** [comment]
Whoa, looks great! Can you get this working in the site itself? (I ask because I was playing with Monaco editor before I opened this issue and ran into trouble. But looks like you'll have more luck than me!)

**Comment by gnidan** [comment]
@raxhvl [here's](https://codesandbox.io/p/sandbox/monaco-editor-json-validation-example-forked-9c44gn?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrejyht100063b6ayv3oias7%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrejyht000023b6ag6khnf3l%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrejyht000033b6avyaht3ih%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrejyht000053b6a2g38qnm3%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrejyht000023b6ag6khnf3l%2522%253A%257B%2522id%2522%253A%2522clrejyht000023b6ag6khnf3l%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clrejyht000053b6a2g38qnm3%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrejyht000043b6axuposn4d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrejyht000053b6a2g38qnm3%2522%252C%2522activeTabId%2522%253A%2522clrejyht000043b6axuposn4d%2522%257D%252C%2522clrejyht000033b6avyaht3ih%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrejyht000033b6avyaht3ih%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) the codesandbox I came up with

**Comment by gnidan** [comment]
I just also found this package, maybe it will work better than @monaco-editor/react: https://github.com/react-monaco-editor/react-monaco-editor
